name: Jules Agent

on: 
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read           
  pull-requests: write     

jobs:
  jules:
    name: Run Jules AI Reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Run Jules
        uses: google-labs-code/jules-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          JULES_AGENT: ${{ secrets.JULES_AGENT }} # 👈 Tambahkan baris ini
